# Large model configuration
_target_: models.lightning_model.ContactPredictionLightningModule

# Model architecture
esm_embedding_dim: 1280
hidden_dim: 1024
num_layers: 6
dropout: 0.2

# Training parameters
learning_rate: 5.0e-5
weight_decay: 1.0e-4

# Loss function parameters
pos_weight: 15.0
alpha: 0.25
gamma: 2.0 